# tests/planning/conftest.py
import pytest
from typing import List, Optional, Set
from uuid import uuid4, UUID

# 假设的导入路径，根据 Specs 调整
from task_graph.planning.domain.aggregates import Task
from task_graph.planning.domain.enums import CompletionLogic, TaskStatus, PlanningLevel
from task_graph.planning.domain.value_objects import TaskId, StoryPoint, ValueScore
from task_graph.planning.domain.ports.task_repository import TaskRepository

class InMemoryTaskRepository(TaskRepository):
    """用于测试的内存 Repository 实现"""
    def __init__(self):
        self._store = {}

    def save(self, task: Task) -> None:
        self._store[task.id.value] = task

    def get(self, task_id: TaskId) -> Optional[Task]:
        return self._store.get(task_id.value)

    def find_all_active(self, project_id: Optional[str] = None) -> List[Task]:
        tasks = [t for t in self._store.values() if t.status != TaskStatus.DONE]
        if project_id:
            tasks = [t for t in tasks if t.project_id == project_id]
        return tasks

    def find_all(self) -> List[Task]:
        return list(self._store.values())

    def find_by_ids(self, task_ids: Set[TaskId]) -> List[Task]:
        return [self._store[tid.value] for tid in task_ids if tid.value in self._store]

    def find_dependents(self, task_id: TaskId) -> List[Task]:
        # 简单遍历实现反向查找
        target_id_str = str(task_id.value)
        return [
            t for t in self._store.values()
            if any(str(d.value) == target_id_str for d in t.dependencies)
        ]
    
    def delete(self, task_id: TaskId) -> None:
        del self._store[task_id]
    
    def find_by_id(self, task_id: TaskId) -> Task | None:
        return self._store.get(task_id.value)

    def find_paged(
        self,
        status: Optional[TaskStatus] = None,
        project_id: Optional[str] = None,
        planning_level: Optional[PlanningLevel] = None,
        search: Optional[str] = None,
        page: int = 1,
        page_size: int = 10,
    ) -> tuple[list[Task], int]:
        tasks = list(self._store.values())

        if project_id:
            tasks = [t for t in tasks if t.project_id == project_id]

        if status:
            tasks = [t for t in tasks if t.status == status]
        if planning_level:
            tasks = [t for t in tasks if t.planning_level == planning_level]
        if search:
            search_lower = search.lower()
            tasks = [
                t for t in tasks
                if search_lower in t.name.lower() or search_lower in t.description.lower()
            ]

        total_count = len(tasks)
        start = (page - 1) * page_size
        end = start + page_size
        return tasks[start:end], total_count

@pytest.fixture
def mock_repo():
    return InMemoryTaskRepository()

@pytest.fixture
def create_task(mock_repo):
    """快速创建 Task 的 Helper"""
    def _factory(project_id="test-project", name="Test Task", effort=1, value=10, logic=CompletionLogic.ALL, deps=None, status=None):
        t = Task.create(
            project_id=project_id,
            name=name,
            description="Generated by fixture",
            completion_logic=logic,
            effort=StoryPoint.create(effort),
            base_value=ValueScore.create(value),
            dependencies=deps or set(),
            planning_level=PlanningLevel.ARCHITECTURAL,
        )
        if status:
            t.status = status
        mock_repo.save(t)
        return t
    return _factory

# --- Graph Fixtures ---

@pytest.fixture
def fixture_linear_graph(create_task):
    # A -> B -> C
    c = create_task(name="C", value=100, effort=5)
    b = create_task(name="B", value=50, effort=3, deps={c.id})
    a = create_task(name="A", value=10, effort=1, deps={b.id})
    return a, b, c

@pytest.fixture
def fixture_diamond_graph(create_task):
    #       Top (Goal)
    #      /   \
    #   Left   Right
    #      \   /
    #     Bottom (Shared)
    bottom = create_task(name="Bottom", value=10, effort=2)
    left = create_task(name="Left", value=20, effort=3, deps={bottom.id})
    right = create_task(name="Right", value=30, effort=3, deps={bottom.id})
    top = create_task(name="Top", value=100, effort=5, deps={left.id, right.id})
    return top, left, right, bottom

@pytest.fixture
def fixture_or_logic_gate(create_task):
    # Goal (OR) -> [Easy (1), Hard (100)]
    easy = create_task(name="Easy Path", effort=1, value=10)
    hard = create_task(name="Hard Path", effort=89, value=10)
    goal = create_task(name="Goal", logic=CompletionLogic.ANY, effort=5, value=100, deps={easy.id, hard.id})
    return goal, easy, hard